/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Fayme Wong (https://sketchfab.com/FaymeWong)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cute-cat-d06965e6712646328129388b32c47b96
title: Cute Cat
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cute_cat.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.defaultMat_0} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/cute_cat.gltf')
